# Site Info
title:              "sSeBBaSs's Littles adventures"
description:        "Sebastian Juarez Personal Site"
google_verify:      dM_ZKxVqXfi38Ib1F1FCXOVbnbKIWWEjh8C8eTlol_8 # Put your Google Verification here
google_analytics:   UA-69227278-1 # Put your Google Analytics code

# Author Info
author_name:        "Sebastian Juarez"
author_email:       ssebbass@gmail.com
author_gravatar:    7e2bd2d3fcf3c7ea07a06233f0a48baf # Gravatar md5 hash
# twitter_username:   HeiswayiNrird

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
page.url:           www.ssebbass.com
permalink:          /notes/:title # Post permalink
timezone:           Americas/Buenos_Aires # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Build
highlighter:        pygments
markdown:           redcarpet
redcarpet:
    extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
#arkdown:           kramdown
#kramdown:
#    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
